#!/usr/bin/env python

import srt
import datetime
import srt_tools.utils
import logging

log = logging.getLogger(__name__)


def timedelta_to_milliseconds(delta):
    return delta.days * 86400000 + \
           delta.seconds * 1000 + \
           delta.microseconds / 1000

def parse_args():
    def srt_timestamp_to_milliseconds(parser, arg):
        try:
            delta = srt.srt_timestamp_to_timedelta(arg)
        except ValueError:
            parser.error('not a valid SRT timestamp: %s' % arg)
        else:
            return timedelta_to_milliseconds(delta)

    parser = srt_tools.utils.basic_parser()
    parser.add_argument(
        '--start',
        type=lambda arg: srt_timestamp_to_milliseconds(parser, arg),
        required=True,
        help='the timestamp when start',
    )
    parser.add_argument(
        '--end',
        type=lambda arg: srt_timestamp_to_milliseconds(parser, arg),
        required=True,
        help='the timestamp when end',
    )
    return parser.parse_args()


def cut_subs(subtitles, overall_start, overall_end):
    for subtitle in subtitles:
        start = timedelta_to_milliseconds(subtitle.start)
        end   = timedelta_to_milliseconds(subtitle.end)
        if overall_start < start and end < overall_end:
            start -= overall_start
            end   -= overall_start
            subtitle.start = datetime.timedelta(milliseconds=start)
            subtitle.end   = datetime.timedelta(milliseconds=end)
            yield subtitle


def main():
    args = parse_args()
    logging.basicConfig(level=args.log_level)
    srt_tools.utils.set_basic_args(args)
    corrected_subs = cut_subs(args.input, args.start, args.end)
    output = srt_tools.utils.compose_suggest_on_fail(
        corrected_subs, strict=args.strict,
    )

    try:
        args.output.write(output)
    except (UnicodeEncodeError, TypeError):  # Python 2 fallback
        args.output.write(output.encode(args.encoding))


if __name__ == '__main__':
    main()
